package org.test.x11.fullscreen;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Created by IntelliJ IDEA.
 * Author: Vladimir Kravets
 * E-Mail: vladimir.kravets-ukr@hp.com
 * Date: 4/12/13
 * Time: 4:16 PM
 */
public class TestForm extends JFrame {
    private JButton button1;
    private JPanel panel1;
    private JButton button2;
    private boolean fullscreen = false;

    public TestForm() {
        $$$setupUI$$$();
        setContentPane(panel1);
        button1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                fullscreen = !fullscreen;
                X11FullscreenHelper.setFullScreenWindow(TestForm.this, fullscreen);
            }
        });
        button2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                ChildDialog dialog = new ChildDialog();
                dialog.pack();
                dialog.setModal(true);
                dialog.setVisible(true);
            }
        });
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        button1 = new JButton();
        button1.setText("Button");
        panel1.add(button1);
        button2 = new JButton();
        button2.setText("Button");
        panel1.add(button2);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
