package org.test.x11.fullscreen;

import com.sun.jna.platform.unix.X11;
import sun.awt.X11.XAtom;
import sun.awt.X11.XBaseWindow;
import sun.awt.X11.XToolkit;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.awt.peer.ContainerPeer;
import java.awt.peer.WindowPeer;

/**
 * Created by IntelliJ IDEA.
 * Author: Vladimir Kravets
 * E-Mail: vladimir.kravets-ukr@hp.com
 * Date: 4/12/13
 * Time: 4:16 PM
 */
public class TestForm extends JFrame {
    private JButton button1;
    private JPanel panel1;
    private JButton button2;
    private boolean fullscreen = false;

    public TestForm() {
        $$$setupUI$$$();
        setContentPane(panel1);
        button1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                fullscreen = !fullscreen;
                XAtom.get("_NET_WM_WINDOW_TYPE").setAtomListProperty((XBaseWindow)TestForm.this.getPeer(), new XAtom[]{XAtom.get("_NET_WM_WINDOW_TYPE_FULLSCREEN")});
//                XAtom.get("_NET_WM_WINDOW_TYPE").DeleteProperty((XBaseWindow)TestForm.this.getPeer());
                XToolkit.awtLock();
                try {
                    X11FullscreenHelper.setFullScreenWindow(TestForm.this, fullscreen);
                } finally {
                    XToolkit.awtUnlock();
                }
           }
        });
        button2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                ChildDialog dialog = new ChildDialog(TestForm.this);
                dialog.pack();
                dialog.setModal(true);
                dialog.setVisible(true);
            }
        });
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        button1 = new JButton();
        button1.setText("Button");
        panel1.add(button1);
        button2 = new JButton();
        button2.setText("Button");
        panel1.add(button2);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
